name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Upload-To-EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 63.32.164.90
          username: ec2-user
          key: ${{ secrets.KEY_NEW }}
          script: |
            echo "Stopping existing Node.js server..."
            PID=$(sudo lsof -t -i:5500)
            if [ ! -z "$PID" ]; then
              echo "Found existing Node.js server with PID: $PID"
              sudo kill -9 $PID
              echo "Existing Node.js server stopped."
            else
              echo "No existing Node.js server running."
            fi
            
            echo "Removing previous repository..."
            rm -rf JobPortalFrontendRepo
            echo "Previous repository removed."

            echo "Cloning new repository..."
            git clone https://github.com/BBDbhagyashrithakur/JobPortalFrontendRepo.git
            echo "New repository cloned."

            echo "Starting Node.js server..."
            sudo nohup node server.js > output.log 2>&1 &
            echo "Node.js server started."
